### ISSUE TITLE
renderer glitches(still there even if its set to opengl)

### ISSUE THREAD

**Issue by ios7jbpro** [Suicide-Squirrel/issues_a10#8]

**Comment by steadfasterX** [comment]
missing:

* exact procedure how to re-produce the issue (which apps, what you do and how,..)
* screenshots or photos which show what you mean
* logs of the time when you get the glitches (see [FAQ#1](https://forum.xda-developers.com/t/rom-unofficial-p-f500-ls991-h81x-us991-vs986-lineageos-16-0.3929082/post-79502871) -> specific issue
 
The LOS FAQ points how to switch between skiagl and opengl: [FAQ#13](https://forum.xda-developers.com/t/rom-unofficial-p-f500-ls991-h81x-us991-vs986-lineageos-16-0.3929082/post-79502871)

from user reports opengl has way less glitches (if any) while skiagl is smoother but can show these more often.

other then that: do not expect a fix for that as it is likely happening due to the poor LG gfx drivers.

closing due to the missing info. feel free to re-open when you get them.
